targets:
  $default:
    builders:
      json_serializable|json_serializable:
        generate_for:
          - lib/core/models/models.dart

      drift_dev|drift_dev:
        generate_for:
          - lib/core/services/local_db_service.dart

      riverpod_generator|riverpod_generator:
        generate_for:
          - lib/features/**/providers/*.dart
          - lib/core/router/*.dart
          - lib/core/services/*.dart